Repository mojohaus/keytool, pull requests merged in 2022-04, with the labels that each got.

#17 setup release drafter, dependabot and gh ci action
  .github/dependabot.yml
  .github/release-drafter.yml
  .github/workflows/maven.yml
  .github/workflows/release-drafter.yml
Labels: enhancement

#16 Allow multiple ext to be specified for GenerateKeyPairMojo, GenerateCertificateRequestMojo, and GenerateCertificateMojo
  keytool-maven-plugin/src/main/java/org/codehaus/mojo/keytool/GenerateCertificateMojo.java
  keytool-maven-plugin/src/main/java/org/codehaus/mojo/keytool/GenerateCertificateRequestMojo.java
  keytool-maven-plugin/src/main/java/org/codehaus/mojo/keytool/GenerateKeyPairMojo.java
Labels: enhancement

#33 use https
  pom.xml
Labels: maintenance

#36 [#35] define plexus-plugin-version.
  pom.xml
Labels: build

#39 [#11] mark Mojos threadsafe.
  keytool-maven-plugin/src/main/java/org/codehaus/mojo/keytool/ChangeAliasMojo.java
  keytool-maven-plugin/src/main/java/org/codehaus/mojo/keytool/ChangeKeyPasswordMojo.java
  keytool-maven-plugin/src/main/java/org/codehaus/mojo/keytool/ChangeStorePasswordMojo.java
  keytool-maven-plugin/src/main/java/org/codehaus/mojo/keytool/CleanKeyMojo.java
  keytool-maven-plugin/src/main/java/org/codehaus/mojo/keytool/DeleteAliasMojo.java
  keytool-maven-plugin/src/main/java/org/codehaus/mojo/keytool/ExportCertificateMojo.java
  keytool-maven-plugin/src/main/java/org/codehaus/mojo/keytool/GenerateCertificateMojo.java
  keytool-maven-plugin/src/main/java/org/codehaus/mojo/keytool/GenerateCertificateRequestMojo.java
  keytool-maven-plugin/src/main/java/org/codehaus/mojo/keytool/GenerateKeyPairMojo.java
  keytool-maven-plugin/src/main/java/org/codehaus/mojo/keytool/GenerateSecretKeyMojo.java
  keytool-maven-plugin/src/main/java/org/codehaus/mojo/keytool/ImportCertificateMojo.java
  keytool-maven-plugin/src/main/java/org/codehaus/mojo/keytool/ImportKeystoreMojo.java
  keytool-maven-plugin/src/main/java/org/codehaus/mojo/keytool/ListMojo.java
  keytool-maven-plugin/src/main/java/org/codehaus/mojo/keytool/PrintCRLFileMojo.java
  keytool-maven-plugin/src/main/java/org/codehaus/mojo/keytool/PrintCertificateMojo.java
  keytool-maven-plugin/src/main/java/org/codehaus/mojo/keytool/PrintCertificateRequestMojo.java
Labels: enhancement

#38 [#37] add README.adoc.
  README.adoc
Labels: documentation

#41 [#40] CI update, builds with IBM Semeru and Java 11, 17
  .github/workflows/maven.yml
Labels: maintenance

#44 [#43] Java 17 requires keyalg argument for generateKeyPair.
  .github/workflows/maven.yml
  keytool-maven-plugin/src/it/MKEYTOOL-10/pom.xml
Labels: build
